language: python
python:
    - "2.7"
    # - "3.6"
    # - "3.7-dev"

services:
  - postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=push.settings_travis
  - export PIP_USE_MIRRORS=true

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - pipenv run push/manage.py test -v 2
