language: python
python:
    - "3.6"

services:
  - postgresql

before_install:
  - export PIPENV_IGNORE_VIRTUALENVS=1

install:
  - pip install pipenv
  - pipenv install --dev

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - mv push/push/settings_travis.py push/push/local_settings.py

script:
  - cd push
  - pipenv run ./manage.py test -v 2
