# Generated by Django 2.0.5 on 2018-05-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_token_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=100, unique=True, verbose_name='Whitelist Token'),
        ),
    ]
